components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
            thread_name: main-worker
        fs-task-processor:
            worker_threads: 2
            thread_name: fs-worker

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: 8080
                task_processor: main-task-processor
        
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: info
                    overflow_behavior: discard

        # Провайдер читает JSON
        default-secdist-provider:
            config: ./configs/secure_data.json

        secdist: {}

        # PostgreSQL (Настройки напрямую)
        postgres-db-1:
            dbconnection: 'postgresql://jobflow_admin:jobflow_pass@127.0.0.1:5432/jobflow_db'
            blocking_task_processor: fs-task-processor
            dns_resolver: async 

        # DNS клиент
        dns-client:
            network-attempts: 3
            fs-task-processor: fs-task-processor

        # Redis
        redis-tasks:
            groups:
              - config_name: redis-tasks # ИЗМЕНЕНО: должно совпадать с ключом в JSON
                db: 0
            subscribe_groups: []
            thread_pools:
                redis_thread_pool_size: 4
                sentinel_thread_pool_size: 1

        # Твои хендлеры
        handler-task-submit:
            path: /v1/tasks/submit
            method: POST
            task_processor: main-task-processor
        handler-task-status:
            path: /v1/tasks/status
            method: GET
            task_processor: main-task-processor
        handler-hello:
            path: /hello
            method: GET,POST
            task_processor: main-task-processor

        # Твои компоненты
        task-scheduler:
        task-worker:

        # Системные компоненты
        testsuite-support: {}
        http-client:
            fs-task-processor: fs-task-processor
        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
        tests-control:
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match